### PR TITLE
Clean up gh-pages

### PR DESCRIPTION
**Pull request by shinaoka**
* Removed old doc from the top directory.
* The user will be redirected from index.html in the top directory to the subdirectory for the master branch in 2 seconds.
* Alternatively, the user can select develop branch.

The content of the top directory looks like this.
.
├── autodoc
├── develop
├── index.html
└── master

### CODE REVIEW

**Comment by yomichi** [comment]
Oops, I found some mistakes in the docs deploy script.
I should fix it before merge this PR, so just a moment.

**Comment by yomichi** [comment]
I removed `autodoc`, `master/dcore_doc`, and `develop/dcore_doc` .

**Comment by shinaoka** [comment]
Everything seems OK!

**Comment by yomichi** [comment]
@shinaoka 

- At the top page, a link name `master` should be renamed to `latest stable` or something.
- I think that we should tell users automatic redirection to the master doc.

**Comment by shinaoka** [comment]
OK, I've add more messages to index.html.

**Comment by yomichi** [comment]
LGTM
:+1:

**Comment by shinaoka** [comment]
Thanks. Pleat merge this PR!

**Pull request merged**
